apiVersion: v1
kind: Service
metadata:
  name: kubernetes-testing-service
  labels:
    app: kubernetes-testing-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: kubernetes-testing-app